#!/usr/bin/env bash
# Regenerate console-test.js from extension/content.js.
#
# The two must never be maintained separately — they differ only in how a repeat
# load is handled:
#   extension : bail out if already loaded (it can be injected twice into one page)
#   console   : tear down the previous instance (pasting twice must work)
# Everything else is identical, so the console build is derived, not written.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

python3 - <<'PY'
import pathlib
src = pathlib.Path("extension/content.js").read_text()
src = src.replace(
'''  if (window.__mctLoaded) return;
  window.__mctLoaded = true;''',
'''  if (window.__mctCleanup) { try { window.__mctCleanup(); } catch (e) {} }
  document.querySelectorAll("#mct-panel").forEach(n => n.remove());''')
src = src.replace('''  console.log(
    "[caption] phase-0 loaded |",''',
'''  window.__mctCleanup = () => {
    if (state.observer) state.observer.disconnect();
    document.querySelectorAll("#mct-panel").forEach(n => n.remove());
  };

  console.log(
    "[caption] phase-0 loaded |",''')
out = pathlib.Path("console-test.js")
out.write_text('// GENERATED by build.sh from extension/content.js - do not edit.\n'
               '// Paste into DevTools console, Teams tab, "top" frame, filter cleared.\n' + src)
print(f"  console-test.js regenerated ({len(out.read_text().splitlines())} lines)")
PY
