#!/usr/bin/env bash
# Regenerate console-test.js from extension/content.js.
#
# The two must never be maintained separately — they differ only in how a repeat
# load is handled:
#   extension : bail out if already loaded (it can be injected twice into one page)
#   console   : tear down the previous instance (pasting twice must work)
# Everything else is identical, so the console build is derived, not written.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

python3 - <<'PY'
import pathlib, sys

src = pathlib.Path("extension/content.js").read_text()

def sub(old, new):
    """Replace exactly once, or stop.

    A plain str.replace that matches nothing does nothing and says nothing. That
    is what happened when the startup log line was reworded: this script kept
    "succeeding" while quietly emitting a console build with no teardown, so a
    second paste stacked a second instance on the first.
    """
    global src
    n = src.count(old)
    if n != 1:
        sys.exit(f"build.sh: pattern matched {n} times, expected 1:\n  {old.strip()[:80]}")
    src = src.replace(old, new)

sub("""  if (window.__mctLoaded) return;
  window.__mctLoaded = true;""",
    """  if (window.__mctCleanup) { try { window.__mctCleanup(); } catch (e) {} }""")

sub("""  console.log(
    "[caption] loaded |",""",
    """  window.__mctCleanup = () => {
    if (state.observer) state.observer.disconnect();
    for (const t of timers) clearInterval(t);
    document.querySelectorAll("#mct-panel, #mct-launcher").forEach(n => n.remove());
  };

  console.log(
    "[caption] loaded |",""")

out = pathlib.Path("console-test.js")
out.write_text('// GENERATED by build.sh from extension/content.js - do not edit.\n'
               '// Paste into DevTools console, Teams tab, "top" frame, filter cleared.\n' + src)
print(f"  console-test.js regenerated ({len(out.read_text().splitlines())} lines)")
PY
